# Generated by Django 2.2.6 on 2019-11-25 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20191117_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='auction',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Item')),
                ('userProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.UserProfile')),
            ],
        ),
    ]
