# Generated by Django 2.2.6 on 2019-11-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20191125_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
