# Generated by Django 2.2.6 on 2019-11-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_item_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='quantity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
